package com.mynews.app.news.openurl

object OpenUrlHost {
    const val DETAIL = "detail"
    const val WEB = "web"
    const val VIDEO = "video"
    const val IMAGE = "image"
    const val MARKET = "market"
    const val TAB = "tab"
    const val SEARCH = "search"
    const val LOGIN = "login"
    const val FEEDBACK = "feedback"
    const val TRACK_EVENT = "track_event"
    const val SAFARI = "safari"
    const val ALERT = "alert"
    const val TOAST = "toast"
    const val ADJUST_TEXT_SIZE = "adjust_text_size"
    const val GIF = "gif"
    const val ESSAY = "essay"
    const val TEXT_SIZE = "text_size"
    const val REQUEST_LOCATION = "request_location"
    const val AUTHORIZATION = "authorization"
    const val WORLDCUP = "world_cup"
    const val MIX_LIST = "mix_list"
    const val PLAYER = "player"
    const val TEAM = "team"
    const val MATCH = "match"
    const val SHARE = "share"
    const val TRACK_SERVER_EVENT = "track_server_event"
}