package com.box.app.news.openurl

object OpenUrlParameter {
    const val ID = "id"
    const val AID = "aid"
    const val REFER = "refer"
    const val REFER_ID = "refer_id"
    const val URL = "url"
    const val INDEX = "index"
    const val FORWARD = "forward"
    const val KEYWORD = "keyword"
    const val TYPE = "type"
    const val PLACEHOLDER_KEYWORD = "placeholder_keyword"
    const val TITLE = "title"
    const val INCLUDES_COMMON_PARAMETERS = "includes_common_parameters"
    const val EVENT = "event"
    const val LABEL = "label"
    const val MESSAGE = "message"
    const val ACTION_TITLE = "action_title"
    const val CONTENT = "content"
    const val STYLE = "style"
    const val PLAYER_ID = "player_id"
    const val TEAM_ID = "team_id"
    const val MATCH_ID = "match_id"
    const val CHID = "chid"
    const val NAME = "name"
    const val TAB = "tab"
    const val SHARE_URL = "share_url"
    const val IMAGE_URL = "image_url"
    const val PLATFORM = "platform"
    const val CHANNEL = "channel"
}